- name: add gpg keys
  apt_key: url={{ item }}
  with_items:
    - https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg
    - https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg

- name: add repository
  get_url: url=https://www.ubuntulinux.jp/sources.list.d/xenial.list
           dest=/etc/apt/sources.list.d/ubuntu-ja.list

- name: update server
  apt: update_cache=yes

- name: install packages for japanese
  apt: pkg={{ item }}
  with_items:
    - ubuntu-defaults-ja
    - language-pack-ja
    - compizconfig-settings-manager

- name: upgrade server
  apt: upgrade=dist

- name: enable fcitx-mozc
  command: im-config -n fcitx

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: set locale ja
  locale_gen:
    name: ja_JP.UTF-8
    state: present
